name: companies-app
region: nyc3
services:
  - name: companies-api-ui
    github:
      repo: ferangarita01/Companies
      branch: master
      deploy_on_push: false # Triggered programmatically via Github Actions after successful test suite
    dockerfile_path: Dockerfile
    http_port: 3100
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PAPERCLIP_DEPLOYMENT_MODE
        value: "authenticated"
      - key: NODE_ENV
        value: "production"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "${DATABASE_URL}"
